name: CI
on:
  push: {}
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install ruby dependencies
      run: |
        gem update --system 3.1.4 -N
        gem install --no-document bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Install node modules
      run: npm install -g @stoplight/spectral@5.9.2
    - name: Run tests
      run: |
        bin/validate-specs.sh
        bin/check-rendering.sh

